### PR TITLE
feat: add rigaya packages

### PR DESCRIPTION
**Pull request by mitosagi**
## Description

Add all plugins from rigaya to the xml. 

## Related Issue

#2 (Don't close)

## How Has This Been Tested?

Load the file with apm and verify the displayed text and installation.

## Checklist:

- [x] The XML file has been formatted by prettier
- [x] Updated the modification date in `mod.xml`.

### CODE REVIEW

**Review by hal-shu-sato — CHANGES_REQUESTED** [review]
I found `?` as `&amp` in `downloadURL`.
I think it is auto-transformation of HTML Specifications.
(I think it may be the specification of `innerText`?)

**Comment by mitosagi** [comment]
It is a specification for XML, not HTML.

**Comment by hal-shu-sato** [comment]
> It is a specification for XML, not HTML.

Wow, I don't know that.
Thank you for letting me know.

**Review by hal-shu-sato — APPROVED** [review]
It was a mistake.

**Comment by hal-shu-sato** [comment]
Also, your Checklist is nice.
I'll make a PR template based on it.

**Pull request merged**
