### PR TITLE
feat: support for data v3

### PR DESCRIPTION
**Pull request by mitosagi**
## Description

This PR contains data in v3 format and JSON Schema.

TypeScript type definitions are generated from JSON Schema when the `yarn fix` command is executed. This type definition should be loaded from apm by npm, which can directly load repositories on github.

## Related Issue

- #122 

## How Has This Been Tested?

- JSON data is automatically generated by https://github.com/hal-shu-sato/apm/pull/469 .
- The data is validated using JSON Schema during CI.
- JSON Schema was visually verified using [JSON Schema Viewer](https://navneethg.github.io/jsonschemaviewer/).

## Checklist:

- [ ] ~~Updated the modification date in `mod.xml`.~~

### CODE REVIEW

**Comment by hal-shu-sato** [comment]
Can you separate a commit editing `package.json` and `yarn.lock`?

And I’m planning to make some breaking changes.
First, change the name of `mod.json` to `list.json`.
Second, change the name of the `isOptional` property to `isUninstallOnly`.
And change some structures. (I'll write them later.)

What do you think about it?

**Comment by mitosagi** [comment]
I think those are good ideas.

In addition to those I would make the following changes.
- Change `obsolute` to `isObsolute`
- Move the `core.xml` `program/releases/release/files/file` currently ignored by apm to `program/files/file` with the (slightly confusing) `isUninstallOnly` flag.

**Comment by hal-shu-sato** [comment]
I wrote this JSON as a plan before.
I want to change the integrity structure as follows JSON.

But I think the version structure should be your (mitosagi's)  plan.
Which do you think is better to handle the data?
And if possible, I'd like @yumetodo to give me your opinion.

```json
    "releases": {
      "1.10": {
        "url": "http://spring-fragrance.mints.ne.jp/aviutl/aviutl110.zip",
        "integrity": {
          "archive": "sha384-YJcXuvmKzJ3nUsGPHaylBdFI9Q4AxAwSDUqpDyZ2wLzYQaU/OE1abw8tMpLf4Jwq",
          "file": [
            {
              "target": "aviutl.exe",
              "hash": "sha384-BsJg59A0t7oHOZp54iljF4nB2V6tYzHiPhYW/h16Oz3qE7qhFFXx6AvhdajnwKfD"
            }
          ]
        }
      },
      "1.00": {
        "url": "http://spring-fragrance.mints.ne.jp/aviutl/aviutl100.zip",
        "integrity": {
          "archive": "sha384-pDm14wvnIx2y4nfsuVJx15k9jTLHGrmTB24m97P5VafHbIXAeFsMRieAfCfASMfi",
          "file": [
            {
              "target": "aviutl.exe",
              "hash": "sha384-TrRFAxOVGtJIhyWV20dXHEOmss96xEHYHaNE4/+t3kvxUGF3IjOP55AnznoNzMom"
            }
          ]
        }
      }
    }
```

**Comment by mitosagi** [comment]
As for the structure of the version, I did so because it seemed more compatible with [react-jsonschema-form](https://github.com/rjsf-team/react-jsonschema-form) to use an array value rather than an associative array.

I will change the integrity structure according to your plan.

**Comment by yumetodo** [comment]
@hal-shu-sato Before starting this schema review, I'd like to ask few questions.

1. Why file integrity is required even though the archive integrity  has been checked? For examle, npm's package-lock.json check the integrity only by package-level integrity(that means archive integrity).
2. When some package was published twice or more with same version, what is expected behavior for apm-data maintainer to update to new one?

**Comment by yumetodo** [comment]
Could it be: file-level integrity is used to detect manual installations?

**Comment by hal-shu-sato** [comment]
@yumetodo 

> @hal-shu-sato Before starting this schema review, I'd like to ask few questions.
> 
> 1. Why file integrity is required even though the archive integrity  has been checked? For examle, npm's package-lock.json check the integrity only by package-level integrity(that means archive integrity).

> Could it be: file-level integrity is used to detect manual installations?

That's true.
We use the file hash to detect packages installed manually.

> 2. When some package was published twice or more with same version, what is expected behavior for apm-data maintainer to update to new one?

I don't expect that situation...
What is the specific case?
The idea I have now is to add a suffix like `-fix1`.

**Comment by yumetodo** [comment]
I'd like to suggest the following structure to express the release date order. 

```json5
"releases": [
  {
    "2.0.1": {
      // something
    },
    "1.8.7": {
      // something
    },
    "2.0.0": {
      // something
    },
    "1.8.6": {
      // something
    },
   // etc...
}
```

**Comment by yumetodo** [comment]
How to detect package conflict which cannot be calculated from the file list? Some plugins use black magic(ex. patch.aul). So, it is required that something like [the `conflicts`/`provides` field of PKGBUILD's one](https://wiki.archlinux.jp/index.php/PKGBUILD#conflicts), I supposed.

**Comment by yumetodo** [comment]
BTW, Why don't you use json5 instead of using pure JSON as a new data format?

**Comment by mitosagi** [comment]
The conflicts and privides fields look very useful, I will add them to the schema.

Do you mean json5 to add comments? V2 XML data contains comments, which complicates the code to update them mechanically. I am considering not including comments in v3 to prevent this.

**Comment by mitosagi** [comment]
I have updated the PR based on the above discussion.

**Comment by mitosagi** [comment]
>> 2. When some package was published twice or more with same version, what is expected behavior for apm-data maintainer to update to new one?

> I don't expect that situation...
> What is the specific case?
> The idea I have now is to add a suffix like `-fix1`.

The semver specification used by apm seems to interpret `1.0.0-fix1` as older than `1.0.0`. Therefore, I would like to use something like `1.0.1-fix1` instead.

**Review by hal-shu-sato — COMMENTED** [review]
I have some points to fix.

And, I have another change, but it is not closely related to this PR, so I will make another PR.

**Pull request merged**
