### PR TITLE
Data v2

### PR DESCRIPTION
**Pull request by hal-shu-sato**
## Description

Change data structure.
This is an idea.
I'd like to discuss this.

### Change

- core.xml
  - Change `/core/${program}/releases` structure  
    - `./release/@version`: The version of the release
    - `./release/url`: The file URL
    - `./release/files`: The additional files of the release (The type is `au:files`)
    - `./release/integrities/integrity`: The integrity of the file
    - `./release/integrities/integrity/@target`: The target of the integrity
- mod.xml
  - Change `packages_list` -> `packages`
- packages.xml
  - Remove `/packages/package/detailURL` element definition
  - Add `/packages/package/releases` element
    - `./release/@version`: The version of the release
    - `./release/files/file`: The additional files of the release (The type is `au:files`)
    - `./release/integrities/integrity`: The integrity of the file
    - `./release/integrities/integrity/@target`: The target of the integrity

## Checklist:

- [x] Updated the modification date in `mod.xml`.

### CODE REVIEW

**Comment by mitosagi** [comment]
I think it's a good data structure and we can go ahead with this.

**Comment by hal-shu-sato** [comment]
Thanks.
I will change the directory structure, the files will be moved.

**Review by mitosagi — COMMENTED** [review]
The data structure is fine.

The integrity seems to be different from mine, but if the same file can be generated differently, I think the command for generation should be unified. I am using the following command to generate the file.
```
cat FILENAME.js | openssl dgst -sha384 -binary | openssl base64 -A
```

**Comment by hal-shu-sato** [comment]
I used the same command...
I don't know why...

**Comment by mitosagi** [comment]
Letting ssri generate sri may absorb differences in environment.

``` javascript
// >node FILENAME.js "C:\Users\***\easymp4.auo"
// This file needs to be run in the apm folder.

const ssri = require('ssri');
const fs = require('fs-extra');

(async () => {
  const args = process.argv.slice(2);
  const readStream = fs.createReadStream(args[0]);
  const str = await ssri.fromStream(readStream, {
    algorithms: ['sha384']
  })
  console.log(str.toString());
  readStream.destroy();
})();
```

**Comment by hal-shu-sato** [comment]
That's right.
I am using Powershell so `cat` is replaced by `Get-Content`. I think that this causes the difference.

**Comment by hal-shu-sato** [comment]
I fixed.
I'll add the script to apm repository as a utility.

**Review by mitosagi — APPROVED** [review]
It looks good.

**Pull request merged**
